#pragma once
#define ENCODER_BTN_PIN GP10
#define RGBLIGHT_LIMIT_VAL 150
#define RGBLIGHT_DEFAULT_MODE  RGBLIGHT_MODE_STATIC_LIGHT
#define RGBLIGHT_DEFAULT_HUE   149
#define RGBLIGHT_DEFAULT_SAT   255
#define RGBLIGHT_DEFAULT_VAL   80
#define I2C_DRIVER I2CD1
#define I2C1_SCL_PIN GP1
#define I2C1_SDA_PIN GP0
#define OLED_TIMEOUT 60000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define DEBOUNCE 5